export const env = {
  SHOPIFY_HOSTNAME: process.env.SHOPIFY_HOSTNAME,
  SHOPIFY_TOKEN: process.env.SHOPIFY_APIKEY,
  CACHE_TOKEN: process.env.CACHE_TOKEN,
  SHOPIFY_GRAPHQL_ENDPOINT: process.env.SHOPIFY_GRAPHQL_ENDPOINT || "",
  SHOPIFY_STOREFRONT_TOKEN: process.env.SHOPIFY_STOREFRONT_TOKEN || "",
  OPENAI_KEY: process.env.OPENAI_KEY || "",
};
